name: Assignment 6 Workflow

on:
  push:
    branches:
      - main  # Update this if you are using a different branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set environment variable
      run: echo "PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Update this with your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have any requirements

    - name: Run tests
      run: |
        python -m pytest -v -W ignore::DeprecationWarning "Assignment - 6"
